//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModeloDatosContainer1 : DbContext
    {
        public ModeloDatosContainer1()
            : base("name=ModeloDatosContainer1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Empleado> EmpleadoSet { get; set; }
        public virtual DbSet<Requerimiento> RequerimientoSet { get; set; }
        public virtual DbSet<Articulo> ArticuloSet { get; set; }
    }
}
